version: '3'
services:
  sliver-server:
    image: byt3bl33d3r/sliver-server:latest
    volumes:
      - ./certs:/certs
      - ./config:/config
      - ./logs:/logs
    ports:
      - "8080:8080"
    environment:
      - SLIVER_CERT=/certs/server/cert.pem
      - SLIVER_KEY=/certs/server/key.pem
